logo: "my_favicon.png"           #---
background: "#750000"    #- color de la navbar
foreground: "#FFFFFF"    #- color navigation elements, text and links that appear in the navbar.
left: 
  - icon: house-door
href: index.html
right:
  - text: "Trabajo"   #---
href: titanic.qmd   
- icon: github
href: https://github.com/padauy    #---
- icon: twitter
href: https://twitter.com/<tu-usuario-twitter>  #---
        #---
page-footer:
  border: true
background: "#e66b63"         #--
left: "© 2022 Luis Antonio Pérez"   #--
center: "Hecho con [Quarto](https://quarto.org)"
right:
  - icon: github
href: https://github.com/padauy 
- icon: twitter
href: https://twitter.com/<tu-usuario-twitter>  #-----
            #-----

format:
  html:
  theme: united
highlight-style: a11y   #-
css: my_styles.css      #- si queréis añadir cosas
page-layout: full
toc: true
code-copy: true
code-overflow: wrap    
code-fold: show
code-line-numbers: true

# Enable CC licence appendix
#license: "CC BY"

lang: es  

# Default execute options
execute:
  echo: true
message: false
warning: false
eval: true

#- Default knitr options
knitr:
  opts_chunk: 
  collapse: true
comment: "#>" 
fig.asp:  7/9
out.width: "95%"
fig.align: "center"
fig.show: "hold"
R.options:
  options(scipen = 999) #- para quitar la notación científica  
